language: ruby
before_install:
 - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
 - sudo apt-get install nodejs
script:
 - bundle exec rake db:migrate RAILS_ENV=test
 - bundle exec rake
